import type { ComparisonInput } from './schema';

export const comparisonDefaults: ComparisonInput = {
  totalDurationSec: 45,
  themeColor: '#22C55E',
  language: 'es',
  audioUrl: 'https://example.com/sample.mp3',
  comparison: {
    toolA: { name: 'CURSOR', color: '#38BDF8' },
    toolB: { name: 'CLAUDE CODE', color: '#F97316' },
    rounds: [
      {
        title: 'Refactor',
        taskDescription: 'Refactorizar función de 80 líneas en módulos separados',
        toolAResult: '✓ Multi-file edit con Composer. Listo en 40 seg.',
        toolBResult: '△ Análisis + plan + edición. Tardó 2 min.',
        winner: 'A',
      },
      {
        title: 'Debug',
        taskDescription: 'Encontrar root cause de una race condition asíncrona',
        toolAResult: '✗ Tab completions. No identificó la causa real.',
        toolBResult: '✓ Trazó el flujo completo. Root cause en 30 seg.',
        winner: 'B',
      },
      {
        title: 'Tests',
        taskDescription: 'Generar tests unitarios para un servicio de pagos',
        toolAResult: '✗ Tests básicos. Sin edge cases de Stripe.',
        toolBResult: '✓ Tests + mocks + edge cases de webhooks.',
        winner: 'B',
      },
      {
        title: 'MCP',
        taskDescription: 'Conectar herramienta externa vía protocolo MCP',
        toolAResult: '✗ Sin soporte nativo. Extensión manual requerida.',
        toolBResult: '✓ Soporte nativo. Config en 5 líneas de JSON.',
        winner: 'B',
      },
    ],
    finalScore: { a: 1, b: 3 },
    overallWinner: 'B',
  },
  segments: [
    {
      index: 0,
      role: 'hook',
      startSec: 0,
      endSec: 2,
      voiceover: 'Cursor vs Claude Code. ¿Cuál es mejor? Cuatro rondas. Un ganador.',
      onScreenText: 'Cursor vs\nClaude Code',
      visualCue: 'hook',
      soundEffect: 'whoosh',
    },
    {
      index: 1,
      role: 'setup',
      startSec: 2,
      endSec: 6,
      voiceover: 'Cuatro pruebas reales: refactor, debug, tests y MCP. Sin favoritismos.',
      onScreenText: '4 pruebas reales',
      visualCue: 'criteria',
    },
    {
      index: 2,
      role: 'development',
      startSec: 6,
      endSec: 13,
      voiceover: 'Ronda uno. Refactor. El Composer de Cursor es difícil de batir.',
      visualCue: 'round-0',
    },
    {
      index: 3,
      role: 'development',
      startSec: 13,
      endSec: 20,
      voiceover: 'Ronda dos. Debug. Claude Code lo destruyó. Root cause en treinta segundos.',
      visualCue: 'round-1',
    },
    {
      index: 4,
      role: 'development',
      startSec: 20,
      endSec: 27,
      voiceover: 'Ronda tres. Tests. Claude Code de nuevo. Los edge cases marcaron la diferencia.',
      visualCue: 'round-2',
    },
    {
      index: 5,
      role: 'development',
      startSec: 27,
      endSec: 34,
      voiceover: 'Ronda cuatro. MCP. No hay discusión. Claude Code tiene soporte nativo.',
      visualCue: 'round-3',
    },
    {
      index: 6,
      role: 'reveal',
      startSec: 34,
      endSec: 40,
      voiceover: 'Resultado final. Cursor uno. Claude Code tres. El ganador es Claude Code.',
      onScreenText: 'CURSOR 1 — CLAUDE CODE 3',
      visualCue: 'final-reveal',
      soundEffect: 'ding',
    },
    {
      index: 7,
      role: 'cta',
      startSec: 40,
      endSec: 45,
      voiceover: '¿Siguen usando Cursor? Comentá por qué.',
      onScreenText: '¿Siguen usando\nCursor? ¿Por qué?',
      visualCue: 'cta',
      soundEffect: 'pop',
    },
  ],
  captions: {
    words: [
      { text: 'Cursor', startMs: 0, endMs: 480 },
      { text: 'vs', startMs: 500, endMs: 680 },
      { text: 'Claude', startMs: 700, endMs: 1020 },
      { text: 'Code.', startMs: 1040, endMs: 1300 },
      { text: '¿Cuál', startMs: 1340, endMs: 1600 },
      { text: 'es', startMs: 1620, endMs: 1760 },
      { text: 'mejor?', startMs: 1780, endMs: 2080 },
      { text: 'Cuatro', startMs: 2200, endMs: 2560 },
      { text: 'pruebas', startMs: 2580, endMs: 2960 },
      { text: 'reales:', startMs: 2980, endMs: 3300 },
      { text: 'refactor,', startMs: 3360, endMs: 3820 },
      { text: 'debug,', startMs: 3840, endMs: 4180 },
      { text: 'tests', startMs: 4200, endMs: 4500 },
      { text: 'y', startMs: 4520, endMs: 4640 },
      { text: 'MCP.', startMs: 4660, endMs: 5000 },
      { text: 'Ronda', startMs: 6100, endMs: 6400 },
      { text: 'uno.', startMs: 6420, endMs: 6700 },
      { text: 'Refactor.', startMs: 6720, endMs: 7180 },
      { text: 'El', startMs: 7220, endMs: 7360 },
      { text: 'Composer', startMs: 7380, endMs: 7840 },
      { text: 'de', startMs: 7860, endMs: 7980 },
      { text: 'Cursor', startMs: 8000, endMs: 8400 },
      { text: 'es', startMs: 8420, endMs: 8560 },
      { text: 'difícil', startMs: 8580, endMs: 8980 },
      { text: 'de', startMs: 9000, endMs: 9140 },
      { text: 'batir.', startMs: 9160, endMs: 9700 },
      { text: 'Ronda', startMs: 13100, endMs: 13400 },
      { text: 'dos.', startMs: 13420, endMs: 13700 },
      { text: 'Debug.', startMs: 13720, endMs: 14080 },
      { text: 'Claude', startMs: 14120, endMs: 14480 },
      { text: 'Code', startMs: 14500, endMs: 14760 },
      { text: 'lo', startMs: 14780, endMs: 14920 },
      { text: 'destruyó.', startMs: 14940, endMs: 15500 },
      { text: 'Root', startMs: 15560, endMs: 15820 },
      { text: 'cause', startMs: 15840, endMs: 16180 },
      { text: 'en', startMs: 16200, endMs: 16360 },
      { text: 'treinta', startMs: 16380, endMs: 16780 },
      { text: 'segundos.', startMs: 16800, endMs: 17400 },
      { text: 'Ronda', startMs: 20100, endMs: 20400 },
      { text: 'tres.', startMs: 20420, endMs: 20700 },
      { text: 'Tests.', startMs: 20720, endMs: 21060 },
      { text: 'Claude', startMs: 21100, endMs: 21460 },
      { text: 'Code', startMs: 21480, endMs: 21740 },
      { text: 'de', startMs: 21760, endMs: 21900 },
      { text: 'nuevo.', startMs: 21920, endMs: 22380 },
      { text: 'Los', startMs: 22440, endMs: 22620 },
      { text: 'edge', startMs: 22640, endMs: 22940 },
      { text: 'cases', startMs: 22960, endMs: 23280 },
      { text: 'marcaron', startMs: 23300, endMs: 23760 },
      { text: 'la', startMs: 23780, endMs: 23940 },
      { text: 'diferencia.', startMs: 23960, endMs: 24700 },
      { text: 'Ronda', startMs: 27100, endMs: 27400 },
      { text: 'cuatro.', startMs: 27420, endMs: 27780 },
      { text: 'MCP.', startMs: 27800, endMs: 28180 },
      { text: 'Claude', startMs: 28220, endMs: 28580 },
      { text: 'Code', startMs: 28600, endMs: 28860 },
      { text: 'tiene', startMs: 28880, endMs: 29160 },
      { text: 'soporte', startMs: 29180, endMs: 29600 },
      { text: 'nativo.', startMs: 29620, endMs: 30160 },
      { text: 'Resultado', startMs: 34100, endMs: 34600 },
      { text: 'final.', startMs: 34620, endMs: 34980 },
      { text: 'Cursor', startMs: 35040, endMs: 35420 },
      { text: 'uno.', startMs: 35440, endMs: 35760 },
      { text: 'Claude', startMs: 35820, endMs: 36160 },
      { text: 'Code', startMs: 36180, endMs: 36440 },
      { text: 'tres.', startMs: 36460, endMs: 36900 },
      { text: '¿Siguen', startMs: 40200, endMs: 40620 },
      { text: 'usando', startMs: 40640, endMs: 41040 },
      { text: 'Cursor?', startMs: 41060, endMs: 41580 },
      { text: 'Comentá', startMs: 41640, endMs: 42080 },
      { text: 'por', startMs: 42100, endMs: 42300 },
      { text: 'qué.', startMs: 42320, endMs: 42860 },
    ],
  },
  brand: {
    handle: '@manunavarro',
  },
};
